spring:
  application:
  name: authentication

  profiles:
    active: local

#server:
#  port: 8090
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5433/database
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: password
#  jpa:
#    hibernate:
#      ddl-auto: none
#  thymeleaf:
#    cache: false
#upload:
#  images: src/main/resources/static/upload/images/
#  csv: src/main/resources/static/upload/csv/
